name: pd-fusion
channels:
  - conda-forge        # community packages
dependencies:
  - python=3.10
  - jupyterlab         # notebooks
  - numpy
  - pandas
  - scikit-learn
  - imbalanced-learn
  - matplotlib
  - pytorch
  - torchvision
  - torchaudio
  - cudatoolkit        # comment out if you’re CPU-only
  - librosa            # audio
  - nibabel            # MRI (NIfTI) I/O
  - pip
  - pip:
      - tqdm           # nice progress bars
